databases:
  - name: ihc-attendance-db
    plan: free

services:
  - type: web
    name: ihc-attendance-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 server.py
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ihc-attendance-db
          property: connectionString
